### ISSUE TITLE
3.2 frame to sound

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#101]
the sound need the 3:2 div, so that in doesn't jump around in the carousel: 
```

<div style="width:100%;padding-bottom:66.6%;position:relative;">                  
   <audio id="background-audio" controls style="outline: none;">
      <source src="https://cdn.hotelkrone.be/artworks/Dont_worry.mp3" type="audio/mpeg">
   </audio>
</div>
```

**Comment by VenzinJonas** [comment]
In a student room or overlay or both ? 

Can you give me some examples ?

**Comment by thelabeljoyves** [comment]
it’s only for the media “void” in the carousel by benjamin gaschen in his Seite

On 26 Jun 2020, at 13:40, Venzin Jonas <notifications@github.com> wrote:


In a student room or overlay or both ?

Can you give me some examples ?

**Comment by cgaspoz** [comment]
C'est quand même pas beau ce petit player :-(

@thelabeljoyves tu penses quoi de ça:
![image](https://user-images.githubusercontent.com/438609/85875471-8923dc80-b7d4-11ea-8db3-ee7c71a46dd9.png)

**Comment by thelabeljoyves** [comment]
oui mais non,
on fait comme c’était
pas de fantaisie: on a fait un check complet ce matin, je veux pas de nouvelles questions :-)


On 26 Jun 2020, at 17:44, Cédric Gaspoz <notifications@github.com> wrote:


C'est quand même pas beau ce petit player :-(

@thelabeljoyves <https://github.com/thelabeljoyves> tu penses quoi de ça:
 <https://user-images.githubusercontent.com/438609/85875471-8923dc80-b7d4-11ea-8db3-ee7c71a46dd9.png>

**Comment by thelabeljoyves** [comment]
Hello

I think we’re good with the website!!! Bravo!

We’re still testing the stream, but that’s all.

love,
Yves


On 26 Jun 2020, at 18:01, Cédric Gaspoz <notifications@github.com> wrote:


Closed #101 <https://github.com/HEG-Arc/HotelKroneHKB/issues/101>.

**Comment by thelabeljoyves** [comment]
now the player is outside of the box, which pushes the whole frame down
I liked the other player with the rounded corners…


On 26 Jun 2020, at 17:44, Cédric Gaspoz <notifications@github.com> wrote:


C'est quand même pas beau ce petit player :-(

@thelabeljoyves <https://github.com/thelabeljoyves> tu penses quoi de ça:
 <https://user-images.githubusercontent.com/438609/85875471-8923dc80-b7d4-11ea-8db3-ee7c71a46dd9.png>

**Comment by cgaspoz** [comment]
Si tu dois changer le player, le style est dans le css:

```
/* AUDIO PLAYER */

.student-player {
  width:100%;
  padding-bottom:32.6%;
  padding-top:30%;
  position:relative;
}

div.student-player #background-audio {
  width: 80%
}
```

**Comment by thelabeljoyves** [comment]
ok, en fait c’est dépendant du browser.
bon, on s’en fiche.
Par contre il faut corriger le fait qu’il soit au-dehors du cadre et pousse le reste de la page vers le bas.

On 26 Jun 2020, at 18:31, Cédric Gaspoz <notifications@github.com> wrote:


Si tu dois changer le player, le style est dans le css:

/* AUDIO PLAYER */

.student-player {
  width:100%;
  padding-bottom:32.6%;
  padding-top:30%;
  position:relative;
}

div.student-player #background-audio {
  width: 80%
}

**Comment by thelabeljoyves** [comment]
Maybe it was all a temporary bug during the working? It was alright some days ago.


On 26 Jun 2020, at 18:31, Cédric Gaspoz <notifications@github.com> wrote:


Si tu dois changer le player, le style est dans le css:

/* AUDIO PLAYER */

.student-player {
  width:100%;
  padding-bottom:32.6%;
  padding-top:30%;
  position:relative;
}

div.student-player #background-audio {
  width: 80%
}

**Comment by cgaspoz** [comment]
Chez moi c'est bon sur tous les browsers. La forme du player c'est lié au browser, c'est chrome qui a un player avec les bords ronds.
Sinon, sur mobile il garde pas le ratio. Tu dois peut-être jouer avec la CSS.

**Comment by thelabeljoyves** [comment]
ni sur le desktop.
mais y eu un moment où c’était réglé.
Y a un truc qu’à cassé qq part


On 26 Jun 2020, at 18:45, Cédric Gaspoz <notifications@github.com> wrote:


Chez moi c'est bon sur tous les browsers. La forme du player c'est lié au browser, c'est chrome qui a un player avec les bords ronds.
Sinon, sur mobile il garde pas le ratio. Tu dois peut-être jouer avec la CSS.

**Comment by cgaspoz** [comment]
Vider le cache du browser? En tout cas, moi j'ai que du tout bon...

# Chrome
![image](https://user-images.githubusercontent.com/438609/85889674-3bb36980-b7ec-11ea-8d30-d6e5a3e1eb94.png)
# Firefox
![image](https://user-images.githubusercontent.com/438609/85889759-5ede1900-b7ec-11ea-89cf-6bdf3a383961.png)
# EDGE
![image](https://user-images.githubusercontent.com/438609/85889821-7f0dd800-b7ec-11ea-8f70-6bab5aa56572.png)
# Chrome Android
![Screenshot_20200626-203540](https://user-images.githubusercontent.com/438609/85889994-cd22db80-b7ec-11ea-88c0-98b2257ded77.png)

**Comment by thelabeljoyves** [comment]
Yes.
Santé :-)

y



On 26 Jun 2020, at 20:38, Cédric Gaspoz <notifications@github.com> wrote:


Vider le cache du browser? En tout cas, moi j'ai que du tout bon...

Chrome

 <https://user-images.githubusercontent.com/438609/85889674-3bb36980-b7ec-11ea-8d30-d6e5a3e1eb94.png>
Firefox

 <https://user-images.githubusercontent.com/438609/85889759-5ede1900-b7ec-11ea-89cf-6bdf3a383961.png>
EDGE

 <https://user-images.githubusercontent.com/438609/85889821-7f0dd800-b7ec-11ea-8f70-6bab5aa56572.png>
Chrome Android

 <https://user-images.githubusercontent.com/438609/85889994-cd22db80-b7ec-11ea-88c0-98b2257ded77.png>
