### ISSUE TITLE
Endless map: set start zoom level

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#12]
Is is possible to define the start zoom level closer into the map?

**Comment by cgaspoz** [comment]
Ajouter les dimensions du fichier image ou le calculer à la volée

# SPA
Carte horizontale, définir le zoom initial à la hauter de la fenêtre

# Garden
Spécifier le niveau de zoom initial (ajouter champ pour la configuration)
