### ISSUE TITLE
virtual space: coordinate system

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#13]
How is the coordinate 0;0 defined?

**Comment by cgaspoz** [comment]
Ajouter le code pour afficher la position de la souris dans la console

https://github.com/pchen66/panolens.js/issues/160

**Comment by cgaspoz** [comment]
Pour afficher la coordonnée X, Y et Z d'un POI sur une image VR, il faut ouvrir la console developper et cliquer sur un point de l'image en maintenant la touche CTRL enfoncée. Les coordonnées X, Y et Z s'affichent alors dans la console.
