### ISSUE TITLE
List Orte

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#14]
The list of Orte is now set. We start in the reception (entrance). The RasterVirtRaum serves the student to see how the file is bent. 
Optional: would it be possible to define the order of the Orte in the entrance? Is it now following the last modified order?

**Comment by cgaspoz** [comment]
Liste des Orte:
- Lobby -> VR + POI
- Lingerie -> VR + POI
- SPA -> MAP (longue bande horizontale) + POI
- Kapelle -> VR + POI
- Park -> MAP + POI (gif animé)
- Terasse -> Restream + POI
- Cinema -> Still image + POI

**Comment by cgaspoz** [comment]
Ajouter un field order pour trier les Orte sur la première page
