### ISSUE TITLE
Support son dans les Orte

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#15]
- Ajouter un field media pour le background sound
- Dans le Orte Lobby, ajouter un bouton play/pause (new POI manuel)

**Comment by cgaspoz** [comment]
Attention, il n'est pas possible de jouer un fichier son <audio autoplay> dans Chrome. Il faut une action de l'utilisateur pour jouer un son ou une vidéo (qui n'est pas mutée).

**Comment by thelabeljoyves** [comment]
ok, ça veut dire qu'il faut un Poi pour faire Play/Pause, non?

**Comment by cgaspoz** [comment]
Oui, pour l'instant il y a le bouton pas beau en haut à gauche de la fenêtre.
