### ISSUE TITLE
Installer service restream

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#17]
https://datarhei.github.io/restreamer/docs/guides-ingest-rtmp.html

- Ingérer feed RTMP de la webcam de l'étudiant
- Avec un token
- Restream pour embed dans le Orte Terassse

**Comment by cgaspoz** [comment]
Voilà, c'est up and running ;-)

![image](https://user-images.githubusercontent.com/438609/82919445-5472fa00-9f76-11ea-9216-ce1cb65acd29.png)

Il faut broadcaster le stream à l'adresse:
- **Server**: rtmp://rtmp.hotelkrone.be/live
- **Stream Key**: terrasse.stream

@thelabeljoyves tu peux contrôler que ça marche?

**Comment by thelabeljoyves** [comment]
Salut Cédric,

cool! il y a un player, mais il y a un probleme a player la video. Aussi, l’image video a une taille fixe, elle ne s’adapte pas à la taille de la fenetre.

à plus
Yves






On 26 May 2020, at 17:36, Cédric Gaspoz <notifications@github.com> wrote:


Voilà, c'est up and running ;-)

 <https://user-images.githubusercontent.com/438609/82919445-5472fa00-9f76-11ea-9216-ce1cb65acd29.png>
Il faut broadcaster le stream à l'adresse:

Server: rtmp://rtmp.hotelkrone.be/live
Stream Key: terrasse.stream
@thelabeljoyves <https://github.com/thelabeljoyves> tu peux contrôler que ça marche?

**Comment by cgaspoz** [comment]
Hi,
Pour avoir de la vidéo, il faut envoyer un stream sur le serveur ;-) comme ça vous pouvez tester si votre stream arrive au moins au bon endroit.

J'ai fait un test avec OBS ce matin et ça marche aussi. Il peut installer OBS sur sa machine et envoyer son stream sans problème. C'est peut-être plus simple pour lui.

Pour la taille, on verra par la suite...

**Comment by thelabeljoyves** [comment]
super, merci,
à plus
Yves

On 27 May 2020, at 08:39, Cédric Gaspoz <notifications@github.com> wrote:


Hi,
Pour avoir de la vidéo, il faut envoyer un stream sur le serveur ;-) comme ça vous pouvez tester si votre stream arrive au moins au bon endroit.

J'ai fait un test avec OBS ce matin et ça marche aussi. Il peut installer OBS sur sa machine et envoyer son stream sans problème. C'est peut-être plus simple pour lui.

Pour la taille, on verra par la suite...

**Comment by cgaspoz** [comment]
Adapter la taille du player à la taille de la fenêtre, en gardant le bon ratio

**Comment by VenzinJonas** [comment]
![image](https://user-images.githubusercontent.com/43850816/84395822-71f2c580-abfe-11ea-9092-395cf95e87cb.png)

il faudra qu'il paramètre la vidéo quand il diffuse 
sur obs -> paramètre -> vidéo : 
- Résolution de base XXX format 3/2
- Résolution de sortie HxW format 3/2
