### ISSUE TITLE
implement test Spa Map

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#18]
Here is a first file for the Spa map
![Spa-map](https://user-images.githubusercontent.com/13436629/83144919-4e0a8c80-a0f4-11ea-98c2-6bb0adf31510.png)

**Comment by cgaspoz** [comment]
Fichier test pour implémenter #1, #11 et #12

**Comment by cgaspoz** [comment]
Il faut définir les bounds en fonction de la taille du `<div id="map"></div>`

Exemple avec taille fixe de l'image:

```
var elmnt = document.getElementById("map");
var bounds = [[0,0], [elmnt.clientHeight,elmnt.clientHeight*16000/1000]];
```
