### ISSUE TITLE
Cinema: poi does not appear

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#23]
there are 2 pois (.jpg & .png) defined for Cinema, yet they do not appear. 
Need to know where is x=0 y=0 and scale (is it defined by the size in pixel of the background?)

**Comment by cgaspoz** [comment]
Need to implement #2 in order to work

**Comment by VenzinJonas** [comment]
Poi image can be placed.
A click on the background image gives x (poi -> position x) and y.
Image remains at base size for now.

**Comment by thelabeljoyves** [comment]
positioning works!
does not scale with background


On 8 Jun 2020, at 11:20, Venzin Jonas <notifications@github.com> wrote:


Poi image can be placed.
A click on the background image gives x (poi -> position x) and y.
Image remains at base size for now.

**Comment by thelabeljoyves** [comment]
positioning works!
yet does not scale with background.
Link in right margin jumped at bottom of page.

**Comment by VenzinJonas** [comment]
it's scale now ! 
To scale correctly, 
it is necessary to fill (Position w  & Position h )in percentage compared to the background image
exemple my img h:100 & w: 200,  the background image (orte) h:2000  & w 1000
Position w : (100/2000)*100 = 5 
Position h : ( 200/1000) 100 = 20 
I already did this for the poi in cinema.
