### ISSUE TITLE
hotelkrone.be ok, www.hotelkrone.be 404

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#24]
www. in front of domain brings a 404, what is to be done. Shall we set up https? If yes, please drop me a link for how-to.

**Comment by cgaspoz** [comment]
C'est bon, j'ai ajouté www.hotelkrone.be dans le fichier de conf. Les deux domaines sont dirigés sur la page d'accueil (www.hotelkrone.be et hotelkrone.be)
