### ISSUE TITLE
Update CSS does not work

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#32]
on dirait que la landing page ne se réfère pas à la css à laquelle j’ai accès avec cyberduck. La nouvelle css n’est pas prise en compte comme sur mon ordi. Et quand j'ai effacée l'ancienne et reloadé dans le browser, la landing page faisait comme si elle avait toujours l'ancienne css.

**Comment by thelabeljoyves** [comment]
la css ne touche plus non plus dev.

**Comment by cgaspoz** [comment]
Hello, il y avait des charactères invalides dans le CSS, je les ai virés. Mais sinon c'est bien le bon CSS qui est utilisé. Il faut que tu essaie de remettre l'ancien fichier qui marchait. Je pense qu'il doit te manquer une directive...

**Comment by thelabeljoyves** [comment]
je viens de te répondre
ahhrh :-)))

y

On 2 Jun 2020, at 18:31, Cédric Gaspoz <notifications@github.com> wrote:


Hello, il y avait des charactères invalides dans le CSS, je les ai virés. Mais sinon c'est bien le bon CSS qui est utilisé. Il faut que tu essaie de remettre l'ancien fichier qui marchait. Je pense qu'il doit te manquer une directive...
