### ISSUE TITLE
Cleanup fonts

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#37]
En cherchant un moyen de servir en local la font Couture qui met des plombes à se charger depuis https://fontlibrary.org/face/couture, j'ai constaté qu'elle n'était pas utilisée :-(

Du coup, après comparaison avec la CSS, il y a 2 imports qui ne sont pas utilisés:

```
<link href="https://fonts.googleapis.com/css?family=Gravitas+One&display=swap" rel="stylesheet">
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/couture" type="text/css"/>
```

Est-ce que l'on peut les virer du template?

**Comment by thelabeljoyves** [comment]
oui
merci

On 4 Jun 2020, at 22:20, Cédric Gaspoz <notifications@github.com> wrote:


En cherchant un moyen de servir en local la font Couture qui met des plombes à se charger depuis https://fontlibrary.org/face/couture <https://fontlibrary.org/face/couture>, j'ai constaté qu'elle n'était pas utilisée :-(

Du coup, après comparaison avec la CSS, il y a 2 imports qui ne sont pas utilisés:

<link href="https://fonts.googleapis.com/css?family=Gravitas+One&display=swap" rel="stylesheet">
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/couture" type="text/css"/>
Est-ce que l'on peut les virer du template?

**Comment by cgaspoz** [comment]
@VenzinJonas tu peux t'en occuper? Dans les deux templates,,,

**Comment by VenzinJonas** [comment]
oui je fais ça
