### ISSUE TITLE
Carousel in Overlay

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#38]
Comme pour une endless map dans l'overlay, je peux aussi implémenter un carousel, non?

**Comment by cgaspoz** [comment]
Oui c'est possible, il faut coller tout le code HTML du carrousel dans le champ embed html du média. Il faut tuner le css.
J'ai fait un exemple https://dev.hotelkrone.be/orte/lobby/
