### ISSUE TITLE
zone sensible non clickable?

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#39]
Est-ce qu'on peut définir une zone sensble (dans un VR), donc où le title apparaît, mais sans qu'on puisse ouvrir d'overlay?

**Comment by cgaspoz** [comment]
Oui, @VenzinJonas il faut ajouter un boolean "hide overlay" qui est False par défaut et on teste quand on prépare l'affichage des infopoints
