### ISSUE TITLE
click counter in media overlay

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#41]
Une étudiante aimerait afficher un compteur de click à côté d'un bouton pour downloader un .zip. Possible? Est-ce que je peux faire le layout et vous implémenter le script?

**Comment by cgaspoz** [comment]
Bof :-(
Il est où ce bouton? C'est un POI, c'est un média?
Il faut implémenter le compteur côté serveur...

**Comment by thelabeljoyves** [comment]
c’est un lien texte vers zip dans un overlay.


On 7 Jun 2020, at 19:44, Cédric Gaspoz <notifications@github.com> wrote:


Bof :-(
Il est où ce bouton? C'est un POI, c'est un média?
Il faut implémenter le compteur côté serveur...
