### ISSUE TITLE
student: media sound does not appear

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#44]
check the media The void by Benjamin Gaschen. I added a transparent image, which puts the tizle at the right place, but no player appears

**Comment by VenzinJonas** [comment]
it works now, there is no need for an image in the media (I deleted it).

**Comment by VenzinJonas** [comment]
![image](https://user-images.githubusercontent.com/43850816/84386144-1968fb80-abf1-11ea-8a7a-ecfc636586ac.png)
the black border ?

**Comment by thelabeljoyves** [comment]
yes
in my brpwser it was blue :-)

On 11 Jun 2020, at 14:38, Venzin Jonas <notifications@github.com> wrote:


 <https://user-images.githubusercontent.com/43850816/84386144-1968fb80-abf1-11ea-8a7a-ecfc636586ac.png>
the black border ?
