### ISSUE TITLE
New html for Overlay

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#49]
New overlay for Orte:
`<div class=overlayframe></div>
    <div class="overlay">
      <a href="..." class="linkoverlay"><img class="overlay-close" src="media/close-white.png"></a>
      <a href="" class="overlay-student linkoverlay">Adriana Bravo</a><span class="overlay-title">Imagine a very lng title that no one wnas to red</span>
      <div class="overlay-content">
        <div class="overlay-element">
          <iframe class="overlay-pdf" src="media/test.pdf#toolbar=0" width="50%" height="500px">
          </iframe>
        </div>
        <p class="overlay-caption">Horse, 24x30x10cm, Bronze.</p>
        <div class="overlay-description">
          Instructions: download the following file <a href="..." class="linkoverlay">mybook.pdf</a> and print it at home on 100% size
        </div>
      </div>
    </div>`

**Comment by cgaspoz** [comment]
A tester avec le nouveau code, il me semble que c'est bon pour le scroll maintenant
