### ISSUE TITLE
Footer homepage & Footer orte/student

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#50]
Homepage:
`<p><span class="spacename"><img class="spacename" src="media/logo-kl.png" width="135px"></span><img src="media/logo-hkb.png" width="130px"></p><p>A project by the <a class="linkund spacename" href="https://www.hkb-gk.ch/de/studiengaenge/ba-fine-arts-114.html">BA Fine Arts</a>hosted by the <a class="linkund spacename" href="//www.kunsthauslangenthal.ch/" target="_blank">Kunsthaus Langenthal</a><a class="linkund spacename" href="">Impressum</a> © by HKB and the authors 2020</p>`

Orte/Student:
`<p>A project by the <a class="linkund spacename" href="https://www.hkb-gk.ch/de/studiengaenge/ba-fine-arts-114.html">BA Fine Arts</a> hosted by the <a class="linkund spacename" href="//www.kunsthauslangenthal.ch/" target="_blank">Kunsthaus Langenthal</a><a class="linkund spacename" href="">Impressum</a> © by HKB and the authors 2020</p>`

**Comment by thelabeljoyves** [comment]
Update Logo in Footer Homepage:
`<p><span class="spacename"><img class="spacename" src="media/logo-hkb.png" width="200px"></span><img src="media/logo-kl.png" width="155px"></p>`
css:
change
.spacename {
  padding-right: 3.5em;
}

**Comment by thelabeljoyves** [comment]
aahrg, update line in footer in both homepage and pages:
`<p>A project by the <a class="linkund spacename" href="https://www.hkb-gk.ch/de/studiengaenge/ba-fine-arts-114.html">BA Fine Arts HKB</a>Hosted by <a class="linkund spacename" href="//www.kunsthauslangenthal.ch/" target="_blank">Kunsthaus Langenthal</a><a class="linkund" href="">Impressum</a></p>`

**Comment by cgaspoz** [comment]
Y'a plus le (c) à la fin?

**Comment by thelabeljoyves** [comment]
non il va dans l’impressum

On 12 Jun 2020, at 14:01, Cédric Gaspoz <notifications@github.com> wrote:


Y'a plus le (c) à la fin?

**Comment by thelabeljoyves** [comment]
footer homepage needs media query class resize:

  <span class="spacename"><img class="spacename footer-hkb" src="/static/media/logo-hkb.38a9d9af5435.png"></span>
  <img class="footer-kl" src="/static/media/logo-kl.f87c4345232d.png">
  </p>
 class uploaded in css
