### ISSUE TITLE
Design: bottom black space on still images

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#53]
The frame and the contents now work on all kind of rooms apart of still images (cinema, reception). Do you see it? I wanted to solve it with a height: 100% on the img, but dont know where to put it.

**Comment by cgaspoz** [comment]
img#backgroundIMG {
    height: 100%;
}

**Comment by thelabeljoyves** [comment]
il faut rajouter ça où? Dans le champ html du Ort?


On 12 Jun 2020, at 09:27, Cédric Gaspoz <notifications@github.com> wrote:


img#backgroundIMG {
height: 100%;
}

**Comment by cgaspoz** [comment]
Déjà ajouté :-)
Si tu actualises ton cache, tu devrais voir la correction...

**Comment by thelabeljoyves** [comment]
trop fort!! :-) that’s my friday

On 12 Jun 2020, at 09:43, Cédric Gaspoz <notifications@github.com> wrote:


Déjà ajouté :-)
Si tu actualises ton cache, tu devrais voir la correction...
