### ISSUE TITLE
change cursor on Hover

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#54]
Hello, a student want the cursor to change when it comes over her element. It is Lea in the Kappelle. I could upload the cursor in media and we can add an html code and css class in the html field of the poi, no?
![png-transparent-white-claw-illustration-beast-t-shirt-bc-bears-claw-scratches-color-tail-location](https://user-images.githubusercontent.com/13436629/84382424-defc6000-abea-11ea-8572-599502dff1d9.png)

**Comment by cgaspoz** [comment]
- Add a css class in the POI definition
- Create the class in the css file
- Upload a media (32x32) in the media folder

This works in fixed and maps. Needs to be fixed in panolens

**Comment by cgaspoz** [comment]
https://pchen66.github.io/Panolens/docs/PANOLENS.Infospot.html#onHover__anchor

**Comment by cgaspoz** [comment]
Custom cursor style is not easily supported on equirectangular images. Works on static and map images.
