### ISSUE TITLE
Improves loading time for medias

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#55]
Medias are quite large and take forever to load...

/static/media are served through https://cdn.hotelkrone.be which is a nginx server behind traefik

What can we do to improve loading time?

**Comment by thelabeljoyves** [comment]
I passed all the pictures into tinyPNG.com

**Comment by cgaspoz** [comment]
Test Thumbor? 
https://hub.docker.com/r/minimalcompact/thumbor
https://web.dev/image-cdns/

**Comment by cgaspoz** [comment]
@thelabeljoyves il faudrait redimensionner toutes les images (hors paralax et map) en max 1800 px de large pour réduire leur taille.
Quand ce sera fait, on pourra refaire des tests de rapidité de chargement. Si ça ne marche toujours pas, on verra pour les servir en plusieurs résolutions en fonction de la taille des écrans (pour ne pas envoyer une image de 1800px sur un smartphone par exemple). Mais ce n'est pas tout à fait élémentaire à faire, donc on essaie déjà de réduire le fichier d'origine.
Pour les orte, on va essayer de les précharger quand tu es dans un orte (le suivant et le précédent). Ce sera plus fluide pour naviguer, sauf si on repasse par l'accueil entre deux...

**Comment by thelabeljoyves** [comment]
il faut que je redimensionne et reloade toutes les images?

On 16 Jun 2020, at 18:26, Cédric Gaspoz <notifications@github.com> wrote:


@thelabeljoyves <https://github.com/thelabeljoyves> il faudrait redimensionner toutes les images (hors paralax et map) en max 1800 px de large pour réduire leur taille.
Quand ce sera fait, on pourra refaire des tests de rapidité de chargement. Si ça ne marche toujours pas, on verra pour les servir en plusieurs résolutions en fonction de la taille des écrans (pour ne pas envoyer une image de 1800px sur un smartphone par exemple). Mais ce n'est pas tout à fait élémentaire à faire, donc on essaie déjà de réduire le fichier d'origine.
Pour les orte, on va essayer de les précharger quand tu es dans un orte (le suivant et le précédent). Ce sera plus fluide pour naviguer, sauf si on repasse par l'accueil entre deux...

**Comment by thelabeljoyves** [comment]
C’est de la folie. J’ai passé les 5 derniers jours à mettre tous les fichiers en ligne.
Est-ce qu’il est possible de faire un dossier avec toutes les images de la base de données. ça je peux automatiser le redimensionnement puis les tinypngiser en bulk, sans changer les noms de fichiers évidemment.
Appelles-moi stp.
Bien à toi
Yves


On 16 Jun 2020, at 18:26, Cédric Gaspoz <notifications@github.com> wrote:


@thelabeljoyves <https://github.com/thelabeljoyves> il faudrait redimensionner toutes les images (hors paralax et map) en max 1800 px de large pour réduire leur taille.
Quand ce sera fait, on pourra refaire des tests de rapidité de chargement. Si ça ne marche toujours pas, on verra pour les servir en plusieurs résolutions en fonction de la taille des écrans (pour ne pas envoyer une image de 1800px sur un smartphone par exemple). Mais ce n'est pas tout à fait élémentaire à faire, donc on essaie déjà de réduire le fichier d'origine.
Pour les orte, on va essayer de les précharger quand tu es dans un orte (le suivant et le précédent). Ce sera plus fluide pour naviguer, sauf si on repasse par l'accueil entre deux...

**Comment by cgaspoz** [comment]
On peut faire passer ceux qui sont déjà sur le serveur dans imagemagick pour les resizer automatiquement, mais tu devras uploader à la main les spécialités qui se sont faites resizer et qui n'auraient pas dû.

Et pour tous les nouveaux fichiers que tu uploade, max 1800px de largeur. Il y a des fichiers qui font plus de 10MB, sur un mobile c'est 7-10 secondes :-(

**Comment by thelabeljoyves** [comment]
En principe toutes les images dans les Seite et les overlay sont passées dans le format 2250x1500px, avec fond blanc (jpg) ou transparent (png), quelque soit leur formats d’origine. Donc oui, ça ne devrait pas être un probleme pour le resizing/optimizing automatique.

Les spécialités devraient être les poi, là il n’y en pas trop et je peux les faire à la main. Vous pouvez les séparer? Sinon je vérifie une fois le processus done.

ça irait?


On 16 Jun 2020, at 19:12, Cédric Gaspoz <notifications@github.com> wrote:


On peut faire passer ceux qui sont déjà sur le serveur dans imagemagick pour les resizer automatiquement, mais tu devras uploader à la main les spécialités qui se sont faites resizer et qui n'auraient pas dû.

Et pour tous les nouveaux fichiers que tu uploade, max 1800px de largeur. Il y a des fichiers qui font plus de 10MB, sur un mobile c'est 7-10 secondes :-(

**Comment by cgaspoz** [comment]
@thelabeljoyves on peut passer toutes les images du dossier artworks (Medias étudiants) dans Imagemagick pour faire le resize (taille, compression, ...).
Pour les autres, on peut faire ça individuellement.

J'ai fait un test, tu peux regarder si c'est bon pour toi?
- Original: https://cdn.hotelkrone.be/artworks/Zusammenhang1.jpg (2096K, 2MB)
- Resized: https://cdn.hotelkrone.be/artworks/Zusammenhang1_TIL.jpg (268K)

On arrive sur cette image à un facteur de 10x!

`convert Zusammenhang1.jpg -resize 1800x1800\> -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB Zusammenhang1_TIL.jpg`

**Comment by thelabeljoyves** [comment]
Hello

on perd quand même en sharpness, ça aplatit l’image vachement.

Est-ce qu'on peut faire:
quality 90
et qu’est-ce que le sampling factor?

Est-ce qu’on fait ça seulement pour les images de plus de 600k ou qqchose du genre? J’ai peur que ça nique les images que j’ai déjà comprimées?

regardes les dernières images que j’ai uploadées ce matin (Kira Mäder)


à plus


On 17 Jun 2020, at 10:03, Cédric Gaspoz <notifications@github.com> wrote:


@thelabeljoyves <https://github.com/thelabeljoyves> on peut passer toutes les images du dossier artworks (Medias étudiants) dans Imagemagick pour faire le resize (taille, compression, ...).
Pour les autres, on peut faire ça individuellement.

J'ai fait un test, tu peux regarder si c'est bon pour toi?

Original: https://cdn.hotelkrone.be/artworks/Zusammenhang1.jpg <https://cdn.hotelkrone.be/artworks/Zusammenhang1.jpg> (2096K, 2MB)
Resized: https://cdn.hotelkrone.be/artworks/Zusammenhang1_TIL.jpg <https://cdn.hotelkrone.be/artworks/Zusammenhang1_TIL.jpg> (268K)
On arrive sur cette image à un facteur de 10x!

convert Zusammenhang1.jpg -resize 1800x1800\> -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB Zusammenhang1_TIL.jpg

**Comment by cgaspoz** [comment]
-sampling-factor horizontal-factorxvertical-factor
sampling factors used by JPEG or MPEG-2 encoder and YUV decoder/encoder.

This option specifies the sampling factors to be used by the JPEG encoder for chroma downsampling. If this option is omitted, the JPEG library will use its own default values. When reading or writing the YUV format and when writing the M2V (MPEG-2) format, use -sampling-factor 2x1 or -sampling-factor 4:2:2 to specify the 4:2:2 downsampling method.

**Comment by cgaspoz** [comment]
@thelabeljoyves nouveau test:
- Original: https://cdn.hotelkrone.be/artworks/Zusammenhang1.jpg (2096K, 2MB)
- Resized: https://cdn.hotelkrone.be/artworks/Zusammenhang1_TIL2.jpg (352K)

avec:

`convert Zusammenhang1.jpg -resize 1800x1800\> -sampling-factor 4:2:0 -strip -quality 90 -interlace JPEG -colorspace RGB Zusammenhang1_TIL2.jpg`

**Comment by thelabeljoyves** [comment]
TOP!

On 17 Jun 2020, at 12:04, Cédric Gaspoz <notifications@github.com> wrote:


@thelabeljoyves <https://github.com/thelabeljoyves> nouveau test:

Original: https://cdn.hotelkrone.be/artworks/Zusammenhang1.jpg <https://cdn.hotelkrone.be/artworks/Zusammenhang1.jpg> (2096K, 2MB)
Resized: https://cdn.hotelkrone.be/artworks/Zusammenhang1_TIL2.jpg <https://cdn.hotelkrone.be/artworks/Zusammenhang1_TIL2.jpg> (352K)
avec:

convert Zusammenhang1.jpg -resize 1800x1800\> -sampling-factor 4:2:0 -strip -quality 90 -interlace JPEG -colorspace RGB Zusammenhang1_TIL2.jpg

**Comment by cgaspoz** [comment]
OK, je lance sur les images dans artworks

**Comment by cgaspoz** [comment]
Toutes les images sont resizées. Les jpg avec imagemagick et les png avec imagemagick et tinypng.
@thelabeljoyves il faut faire gaffe à passer toutes les nouvelles images dans tinypng et leur donner une taille max de 1800.

**Comment by thelabeljoyves** [comment]
cool!
yep, je fais gaffe :-)




On 19 Jun 2020, at 17:23, Cédric Gaspoz <notifications@github.com> wrote:


Toutes les images sont resizées. Les jpg avec imagemagick et les png avec imagemagick et tinypng.
@thelabeljoyves <https://github.com/thelabeljoyves> il faut faire gaffe à passer toutes les nouvelles images dans tinypng et leur donner une taille max de 1800.
