### ISSUE TITLE
Endless map in Overlay

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#56]
the media d'Adriana Bravo "Sleeping human VIII, 2020" should be on original size with scrolls in the overlay.

**Comment by cgaspoz** [comment]
Add boolean to add specific class

**Comment by VenzinJonas** [comment]
it's working but i set the height at 200px. Doesn't work with %

**Comment by thelabeljoyves** [comment]
is there a possibility to set the start point of the image? See png attached
![Screen Shot 2020-06-25 at 09 07 58](https://user-images.githubusercontent.com/13436629/85688641-3661fc00-b6d2-11ea-9946-1caa1917527c.png)
