### ISSUE TITLE
overlay: img inherit opacity -> change in class

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#58]
the img in the overlay inherits the opacity:98% of the overlay definition. is it enough to adapt the class and add opacity:100% ?
```
.overlay-element{
  opacity: 100%; 
  width: 100%;
  margin: auto;
}
```

**Comment by cgaspoz** [comment]
Done, tell me if it's better now!

**Comment by thelabeljoyves** [comment]
Hello

for now the media is still transparent (chrome, firefox,weirdly enough the whole layer is opaque in Safari). Check for example in the park, the media in “Triggerbuch”.

Now, before changing this, wait a minute – they are currently discussing if they prefer to keep the whole layer opaque, which is a simple change in the css. So keep this issue on hold for now.


On 16 Jun 2020, at 19:16, Cédric Gaspoz <notifications@github.com> wrote:


Done, tell me if it's better now!
