### ISSUE TITLE
Lobby: disappearing pois

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#60]
In the lobby the pois tend to disappear, although the cursor reacts. Too heavy images?

**Comment by thelabeljoyves** [comment]
Hello, pois in equilateral will all be transparent surfaces, so no need to fix the disappearing pois

**Comment by VenzinJonas** [comment]
the poi disappear when you do a right click ? or there are other cases ?

**Comment by thelabeljoyves** [comment]
Hello, it shortly appears when the camera “arrives” on it, then disappears, although the area stay sensitive. It only happens with the 2 pois in lobby when you turn to the left. The poster and the fridge are ok, which is weird – but we have decided to insert the images into the background, and only use transparent pois, which means that the issue is no longer a problem.

What I need though is the positionning system through the console to find out the position for the pois.


On 17 Jun 2020, at 09:50, Venzin Jonas <notifications@github.com> wrote:


the poi disappear when you do a right click ? or there are other cases ?
