### ISSUE TITLE
Orte: on hover poi display name poi only

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#62]
Now on hover it shows the name of the poi and the media. It would be better if it shows only the name of the poi.

**Comment by VenzinJonas** [comment]
Just the name of the poi or also the name of the student?
Actually: 
 poi name | media name (will be erase ) | name of the student

**Comment by thelabeljoyves** [comment]
hello

only poi name


On 17 Jun 2020, at 09:32, Venzin Jonas <notifications@github.com> wrote:


Just the name of the poi or also the name of the student?
Actually:
poi name | media name (will be erase ) | name of the student

**Comment by thelabeljoyves** [comment]
Can you send me the the full style definition of the .panolens-infospot ? I need to put it complete, apart of font-family & weight in the css so that they are identical in map and vr.

**Comment by VenzinJonas** [comment]
I'don't find the class definition but this is the style apply : 

display: none;
color: rgb(255, 255, 255);
top: 0px;
max-width: 50%;
max-height: 50%;
text-shadow: rgb(0, 0, 0) 0px 0px 3px;
font-family: "Trebuchet MS", Helvetica, sans-serif;
position: absolute;
transform: translate(361.5px, 410px);

**Comment by thelabeljoyves** [comment]
ok, this is done
thanks
y
On 26 Jun 2020, at 13:37, Venzin Jonas <notifications@github.com> wrote:

display: none;
color: rgb(255, 255, 255);
top: 0px;
max-width: 50%;
max-height: 50%;
text-shadow: rgb(0, 0, 0) 0px 0px 3px;
font-family: "Trebuchet MS", Helvetica, sans-serif;
position: absolute;
transform: translate(361.5px, 410px);
