### ISSUE TITLE
Seiten: correct last link: portofolio in portfolio

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#64]

**Comment by cgaspoz** [comment]
@thelabeljoyves more information?

**Comment by thelabeljoyves** [comment]
sorry. On the seite there is the last link where the portfolio can be dowloaded. Now it is written “portofolio” and it should be “portfolio” :-)


On 16 Jun 2020, at 21:36, Cédric Gaspoz <notifications@github.com> wrote:


@thelabeljoyves <https://github.com/thelabeljoyves> more information?
