### ISSUE TITLE
Orte: Pavillon not on homepage list

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#65]
Is it possible that Pavillon does not appear on the homepage?

**Comment by cgaspoz** [comment]
Yes, check the "Hide on entrance" box!

**Comment by thelabeljoyves** [comment]
thanks

On 16 Jun 2020, at 21:42, Cédric Gaspoz <notifications@github.com> wrote:


Yes, check the "Hide on entrance" box!
