### ISSUE TITLE
Mettre à jour le texte de l'impressum

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#67]

**Comment by cgaspoz** [comment]
@thelabeljoyves c'est maintenant dans l'admin dans Contents management, au même endroit que pour le programme. Full HTML.

**Comment by thelabeljoyves** [comment]
nice!

On 17 Jun 2020, at 18:34, Cédric Gaspoz <notifications@github.com> wrote:


@thelabeljoyves <https://github.com/thelabeljoyves> c'est maintenant dans l'admin dans Contents management, au même endroit que pour le programme. Full HTML.
