### ISSUE TITLE
Fix #room 2:3 ratio

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#7]

**Comment by thelabeljoyves** [comment]
ç'a l'air ok. Faut encore jouer avec la marge bottom en lui mettant height=98%
Par contre attention, la landing page est toute noire! :-)

**Comment by cgaspoz** [comment]
Ajouté <div id="keycontent"></div> sur la langing, affichage OK

**Comment by thelabeljoyves** [comment]
OUF! :-) Merci beaucoup!!!

biz
Yves

On 19 May 2020, at 08:28, Cédric Gaspoz <notifications@github.com> wrote:


Ajouté

sur la langing, affichage OK

**Comment by cgaspoz** [comment]
Il faut encore ajouter la hauteur de #room dans le CSS:

```
#room {
  height: 98%
}
```
