### ISSUE TITLE
Defines initial camera position in panolens

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#72]

**Comment by cgaspoz** [comment]
Utiliser position x et y du Orte pour entrer les coordonnées?

**Comment by VenzinJonas** [comment]
oui centre la caméra sur Orte -> position x,y et z

**Comment by thelabeljoyves** [comment]
top!

On 18 Jun 2020, at 11:29, Venzin Jonas <notifications@github.com> wrote:


oui centre la caméra sur Orte -> position x,y et z
