### ISSUE TITLE
scaling pois in map (Park)

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#79]
Hello, I forgot yesterday: the pois in the map are not scaling with the map. There was an issue and a solution, but can't find it back. What was the solution?

**Comment by cgaspoz** [comment]
There is a solution in #23. Can you try it?

> To scale correctly,
> it is necessary to fill (Position w & Position h )in percentage compared to the background image
> exemple my img h:100 & w: 200, the background image (orte) h:2000 & w 1000
> Position w : (100/2000)*100 = 5
> Position h : ( 200/1000) 100 = 20
> I already did this for the poi in cinema.

**Comment by thelabeljoyves** [comment]
This issue has absolute priority.

Solution from #23 does not work. The position given in the console on click is not consistent with the size of the file, which is the same as w and h in the backend. Also the mapping does not fit the height of the map.

Also, the position changes when changing the size of the browser window, which makes it impossible to set a stable poi, not even by pure trial and error.

Poi "klangschale" has the px size of the object in the original illustrator file and is configured in the backend like in Cinema (which becomes extreme as w=(506/14634)*100=3 as decimals are not allowed), following solution from #23.

**Comment by thelabeljoyves** [comment]
The maps should also follow resize of the window, otherwise we get a weird space around the map when the window is resized bigger. If not possible, check if the background can be set to black. 

Maybe we need to thing specifically the 2 maps, Spa and Park. Park should start at zoom level 2 anyway, with no possibilty to zoom out, so there might be no need for a resize. 
For Spa, maybe the map is not the right solution, but rather a horizontal scroll that is not visible.

**Comment by thelabeljoyves** [comment]
Hello, Update:
Both map, Park and Spa, should have a fix z position (no zoom in or out). So in fact we don't have a scaling problem, only position. 

The z position of spa is already set, we just need it to follow the size of the browser window. For now works very well on mobile and tablet. 

The Park is centered on the blue fountain and the zoom level should be fixed at level 2

**Comment by VenzinJonas** [comment]
Hello, 
I changed the positions of poi to make it relative. So now the poi stay in their place.
To place them, click on the map gives x, y (poi -> position_x and position_y)

The zoom is now blocked. The map adapts to the size of the window only when the page loads (f5)
