### ISSUE TITLE
Test re:restream tonight

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#82]
Hello, we will make a test of the stream tonight at 21h. Can you make sure the server is running? Thanks

**Comment by cgaspoz** [comment]
It's always running ;-) You only need to provide a stream.

I will be around tonight, so you can call me if you have issues with the streaming...

**Comment by thelabeljoyves** [comment]
Top, thank you!

On 19 Jun 2020, at 15:51, Cédric Gaspoz <notifications@github.com> wrote:


It's always running ;-) You only need to provide a stream.

I will be around tonight, so you can call me if you have issues with the streaming...

**Comment by cgaspoz** [comment]
Someone here? No stream so far :-(

**Comment by cgaspoz** [comment]
![2020-06-19 21_29_29-Paramètres](https://user-images.githubusercontent.com/438609/85174268-537f7080-b275-11ea-9c35-7976b2f85c6b.png)
![2020-06-19 21_30_07-Paramètres](https://user-images.githubusercontent.com/438609/85174274-5712f780-b275-11ea-9de9-564a5d4af5fa.png)
![2020-06-19 21_30_29-Paramètres](https://user-images.githubusercontent.com/438609/85174284-5a0de800-b275-11ea-8919-a3dc5fdacf55.png)
![2020-06-19 21_30_57-Paramètres](https://user-images.githubusercontent.com/438609/85174322-6bef8b00-b275-11ea-8593-9ae673841671.png)

**Comment by thelabeljoyves** [comment]
ok, ça marche. On soupçonne une rallonge USB 2.0. est-ce que tu peux encore integrer l'autoplay dans le player? merci et bonne baignade: 
Autoplay
If want to enable autoplay, simply tick the box “Autoplay” in the Restreamer GUI or add ?autoplay=1 after player.html such that it looks like this:

`<iframe src="http://.../player.html?autoplay=1" ...></iframe>`

**Comment by cgaspoz** [comment]
Ajouté ?autoplay=1 dans Zimmer

**Comment by cgaspoz** [comment]
Attention, le mot de passe admin a changé le 23.06, cf. email
