### ISSUE TITLE
html page for video before launch uploaded

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#85]
I uploaded the file videointro.html with an embedded vimeolink

**Comment by cgaspoz** [comment]
Argh l'encodage :-(
Je vais corriger ça...

**Comment by thelabeljoyves** [comment]
de l’html?

On 23 Jun 2020, at 08:50, Cédric Gaspoz <notifications@github.com> wrote:


Argh l'encodage :-(
Je vais corriger ça...

**Comment by cgaspoz** [comment]
![image](https://user-images.githubusercontent.com/438609/85371862-3d9dd400-b531-11ea-9180-1c50e55cc77f.png)

**Comment by thelabeljoyves** [comment]
ah mince!
faut que j’aprenne ça, pas encore bien compris.
merci :-)

On 23 Jun 2020, at 09:09, Cédric Gaspoz <notifications@github.com> wrote:


 <https://user-images.githubusercontent.com/438609/85371862-3d9dd400-b531-11ea-9180-1c50e55cc77f.png>

**Comment by cgaspoz** [comment]
- Ajouté la définition de l'encodage
- Corrigé les liens des images
- Ajouté le tracker
- Supprimé les <a href> sur les noms des étudiant·es
