### ISSUE TITLE
analytics tracking code & cookie warning

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#86]
here is the tracking code:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-170145026-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-170145026-1');
</script>
```
In this regard: do we have to make a cookie warning overlay? :-/

**Comment by cgaspoz** [comment]
Not in Switzerland, but yes in the EU. As this is an EU domain, you probably have to...

Other option is to run a local analytics software like:
- https://matomo.org/
- http://www.openwebanalytics.com/

**Comment by thelabeljoyves** [comment]
- google analytics seems to be the only possible problem. I will check further on this
- .be is not a problem, the website is hosted in CH and operated by CH. Swiss law works for us.
- yet I read that https is compulsory, can we implement this?


On 23 Jun 2020, at 09:07, Cédric Gaspoz <notifications@github.com> wrote:


Not in Switzerland, but yes in the EU. As this is an EU domain, you probably have to...

Other option is to run a local analytics software like:

https://matomo.org/ <https://matomo.org/>
http://www.openwebanalytics.com/ <http://www.openwebanalytics.com/>

**Comment by cgaspoz** [comment]
https is already on

**Comment by thelabeljoyves** [comment]
cooool

On 23 Jun 2020, at 09:55, Cédric Gaspoz <notifications@github.com> wrote:


https is already on

**Comment by cgaspoz** [comment]
Stats are now available from: https://stats.hotelkrone.be/

**Comment by thelabeljoyves** [comment]
ok, so do I cancel the google analytics tool?

On 23 Jun 2020, at 11:49, Cédric Gaspoz <notifications@github.com> wrote:


Stats are now available from: https://stats.hotelkrone.be/ <https://stats.hotelkrone.be/>

**Comment by cgaspoz** [comment]
Yes you can now
