### ISSUE TITLE
html code for overlay video fullscreen

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#87]
The new classes are uploaded. Here is the html for the fullscreen video overlay

```
<!-- overlay fullscreen -->
          <div class=overlayframe-fs>
            <div class="overlay-fs">
              <div class="overlay-topline-fs">
                <a href="..." class="linkoverlayclose overlay-close-fs overlay-back-txt"> X </a>
                <a href="" class="overlay-student-fs linkoverlay overlay-back-txt">Lea Luzifer</a><span class="overlay-title-fs overlay-back-txt">TV Show</span>
              </div>
              <div class="overlay-content-fs w-100">

                  <div style="width:100%;padding-bottom:56.25%;position:relative;">
                    <iframe src="https://player.vimeo.com/video/429906122/?title=0&byline=0&portrait=0" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
                  </div><script src="https://player.vimeo.com/api/player.js"></script>

              </div>
            </div>
          </div>
          <!-- Fin fullscreen -->
```

**Comment by cgaspoz** [comment]
Il manque le style **overlay-topline-fs** dans la stylesheet

```
root@v2202005112624116841:/home/hkb/media/css# less master-hk.css | grep .-fs
.overlayframe-fs {
.overlay-fs{
.overlay-student-fs{
.overlay-title-fs{
.overlay-close-fs{
.overlay-content-fs{
```

**Comment by thelabeljoyves** [comment]
merci – je dois de toute refaire tout l’overlay, pas content de comment il est maintenant.

On 23 Jun 2020, at 22:37, Cédric Gaspoz <notifications@github.com> wrote:


Il manque le style overlay-topline-fs dans la stylesheet

root@v2202005112624116841:/home/hkb/media/css# less master-hk.css | grep .-fs
.overlayframe-fs {
.overlay-fs{
.overlay-student-fs{
.overlay-title-fs{
.overlay-close-fs{
.overlay-content-fs{

**Comment by cgaspoz** [comment]
Video in https://hotelkrone.be/videointro.html is set to autoplay on load:

`src="https://player.vimeo.com/video/430785674?title=0&byline=0&portrait=0&autoplay=1&loop=1&muted=1"`

**Comment by thelabeljoyves** [comment]
The overlay is made of 3 elements added in the page. Hope this is possible:
in `<div id="title-hotel">`
after `<a href="index-hotelkrone.html"> ...</a>`
add `<span class="close-video"><a href="" class="linknames">X</a></span>` 

in `<div id="keycontent">`
after `<div id="keycase">`
add `<div id="keycase-video"></div>` where comes the embed code

in `<div id="groundtext">`
add `<span class="caption-video"></span>` where comes the legend of the media

**Comment by thelabeljoyves** [comment]
new classes uploaded in the CSS

**Comment by thelabeljoyves** [comment]
delete the field `<span class="caption-video"></span>` in `<div id="groundtext">` in the fullscreen overlay
