### ISSUE TITLE
Landing page: new version

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#89]
please upload the new landing page with program today Wed 24.6. Can't do it, permission denied by cyberduck.

[index.html.zip](https://github.com/HEG-Arc/HotelKroneHKB/files/4822022/index.html.zip)

**Comment by cgaspoz** [comment]
Done,
Ajouté l'encodage: `<meta http-equiv="Content-Type"   content="text/html; charset=UTF-8">`
Ajouté le code du tracker Matomo

**Comment by thelabeljoyves** [comment]
merci, tu me donneras une fois un mini cours sur cet encodage? je pensais tjrs que maintenant y plus besoin de s’en occuper … :-)

On 24 Jun 2020, at 09:32, Cédric Gaspoz <notifications@github.com> wrote:


Done,
Ajouté l'encodage: <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
Ajouté le code du tracker Matomo
