### ISSUE TITLE
Update templates Student & Orte

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#9]
I updated the templates, redefining and creating new classes and ids.
- in general the frame has bee reduced, so as to give more space to the center
- the student template has the same structure but with its own set of classes
- in the orte template the overlay has been redefined
- the id key-content has been integrated. It needs to be uploaded and implemented so I can fine tune the height.
[untitled folder.zip](https://github.com/HEG-Arc/HotelKroneHKB/files/4675327/untitled.folder.zip)

**Comment by thelabeljoyves** [comment]
forgot to integrate: 

#room {
  height: 98%
}

**Comment by thelabeljoyves** [comment]
Update overlay definition: 

<div class=overlayframe></div>
    <div class="overlay">
      <a href="student3-bravo.html" class="overlay-student linkoverlay">Adriana Bravo</a>
      <a href="..." class="overlay-close linkrooms"><img src="media/close-lay.png" width="20px"></a>
      <div class="overlay-content">
        <span class="overlay-title">Horse</span>
        <div class="overlay-element">
          <iframe class="overlay-pdf" src="media/test.pdf#toolbar=0" width="50%" height="500px">
          </iframe>
        </div>
        <p class="overlay-caption">Horse, 24x30x10cm, Bronze.</p>
        <div class="overlay-description">
          Instructions: download the following file <a href="..." class="linkoverlay">mybook.pdf</a> and print it at home on 100% size
        </div>
      </div>
    </div>

**Comment by thelabeljoyves** [comment]
obsolete

**Comment by thelabeljoyves** [comment]
Use this zipped
[Uploading HKbe.zip…]()
 package

**Comment by thelabeljoyves** [comment]
Hello, vous arriveriez à fixer la ratio 3/2 des Orte et Homepage (pour qu'il n'y ait plus la barre noire dessous) jusqu'à demain 10h? Merci, bien à vous

**Comment by VenzinJonas** [comment]
Hello, pas de soucis. Je vais regarder si j'arrive à corriger ça avant 10 h.

**Comment by thelabeljoyves** [comment]
Merci beaucoup!

**Comment by thelabeljoyves** [comment]
Hello Jonas,
tu penses y arriver encore ce matin?
bien à toi
Yves


On 8 Jun 2020, at 18:27, Venzin Jonas <notifications@github.com> wrote:


Hello, pas de soucis. Je vais regarder si j'arrive à corriger ça avant 10 h.

**Comment by VenzinJonas** [comment]
on vient de régler partiellement le problème

**Comment by thelabeljoyves** [comment]
hello, là y a plus rien à voir, sauf pour les images fixes.





On 9 Jun 2020, at 11:43, Venzin Jonas <notifications@github.com> wrote:


on vient de régler partiellement le problème
