### ISSUE TITLE
Show POI name on hover in maps and still images

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#94]

**Comment by thelabeljoyves** [comment]
font-family:'Source Sans Pro';
font-weight:300;

**Comment by cgaspoz** [comment]
Adds a new "panolens-infospot" class in CSS

**Comment by thelabeljoyves** [comment]
css added

**Comment by thelabeljoyves** [comment]
css added

**Comment by thelabeljoyves** [comment]
Hello Jonas, can you send me the complete style definition of the panolens
infospot class? I'll put it complete in the Css, apart of font-family, so
that the caption in the maps look like the one in the VRspaces.
Thank you
