### ISSUE TITLE
Map intermediate zoom level (1.5)

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/HotelKroneHKB#95]
**Fractional zoom**
A feature introduced in Leaflet 1.0.0 was the concept of fractional zoom. Before this, the zoom level of the map could be only an integer number (0, 1, 2, and so on); but now you can use fractional numbers like 1.5 or 1.25.

Fractional zoom is disabled by default. To enable it, use the map’s zoomSnap option. The zoomSnap option has a default value of 1 (which means that the zoom level of the map can be 0, 1, 2, and so on).

If you set the value of zoomSnap to 0.5, the valid zoom levels of the map will be 0, 0.5, 1, 1.5, 2, and so on.

If you set a value of 0.1, the valid zoom levels of the map will be 0, 0.1, 0.2, 0.3, 0.4, and so on.

The following example uses a zoomSnap value of 0.25:

```
var map = L.map('map', {
    zoomSnap: 0.25
});
```

https://leafletjs.com/examples/zoom-levels/

**Comment by thelabeljoyves** [comment]
<img width="1440" alt="Screen Shot 2020-06-24 at 11 42 19" src="https://user-images.githubusercontent.com/13436629/85532224-cf7c0e80-b60f-11ea-8942-b8be781118a2.png">

**Comment by thelabeljoyves** [comment]
ça marche super!

On 24 Jun 2020, at 17:56, Venzin Jonas <notifications@github.com> wrote:


Closed #95 <https://github.com/HEG-Arc/HotelKroneHKB/issues/95>.
