### ISSUE TITLE
keep programm closed on homepage

### ISSUE THREAD

**Issue by thelabeljoyves** [HEG-Arc/HotelKroneHKB#97]
keep the programm closed for the rest of the session, and not show up once one returns to the homepage to go to wherever else.

**Comment by cgaspoz** [comment]
Program opens only once in 24h (cookie expiration)
Added a link after impressum, to display the program

**Comment by thelabeljoyves** [comment]
programm loaded every time when going back on homepage

**Comment by cgaspoz** [comment]
Cassé par le commit 00bac7f15b390ba806fc84748dc67be471c8cd2a @VenzinJonas

**Comment by thelabeljoyves** [comment]
en profiter pour checker: dans chrome, quand on ferme le programm, le cadre bouge. ça ne le faisait pas avant.
